[package]
name = "polecen-macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.26"
syn = { version = "1.0.72", features = ["full"] }
quote = "1.0.9"
convert_case = "0.4.0"
