name: lib
on:
  push:
    branches:
      - master
    paths:
      - 'polecen/**'
      - 'polecen-macros/**'
  pull_request:
    paths:
      - 'polecen/**'
      - 'polecen-macros/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check macros
      run: cargo check --verbose
      working-directory: polecen-macros
    - name: Check lib
      run: cargo check --verbose
      working-directory: polecen
